version: '3.11'
services:
  web:
    build: ./main
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./main/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=rest_api_blog
      - POSTGRES_PASSWORD=rest_api_blog
      - POSTGRES_DB=rest_api_blog
volumes:
  postgres_data: