# Generated by Django 4.1.3 on 2022-11-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_banner', models.ImageField(upload_to='images/', verbose_name='Баннер на странице')),
                ('about_title', models.CharField(max_length=60, verbose_name='Заголовок на странице')),
                ('about_text', models.TextField(verbose_name='Описание на странице')),
            ],
            options={
                'verbose_name': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='TeamAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('team_post', models.CharField(max_length=100, verbose_name='Должность')),
                ('team_text', models.TextField(verbose_name='Описание')),
                ('team_photo', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('team_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('team_draft', models.BooleanField(default=True, verbose_name='Публикация')),
                ('team_on_about', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team_id', to='about.about')),
            ],
            options={
                'verbose_name': 'Команда',
            },
        ),
        migrations.CreateModel(
            name='AboutBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_icon', models.CharField(choices=[('fas fa-bezier-curve fa-4x tm-color-primary', 'иконка 1'), ('fas fa-users-cog fa-4x tm-color-primary', 'иконка 2'), ('fab fa-creative-commons-sampling fa-4x tm-color-primary', 'иконка 3')], max_length=60, verbose_name='Иконка')),
                ('benefit_title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('benefit_text', models.TextField(verbose_name='Описание приемущества')),
                ('benefit_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('benefit_draft', models.BooleanField(default=True, verbose_name='Публикация')),
                ('benefits_on_about', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='benefits_id', to='about.about')),
            ],
            options={
                'verbose_name': 'Приемущества',
            },
        ),
    ]
