# Generated by Django 4.1.3 on 2022-11-28 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutbenefit',
            options={'verbose_name': 'Приемущества', 'verbose_name_plural': 'Приемущества'},
        ),
        migrations.AlterModelOptions(
            name='teamabout',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команда'},
        ),
    ]
