# Generated by Django 4.1.3 on 2022-11-25 10:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=80, verbose_name='Название категории')),
                ('category_slug', models.SlugField(unique=True, verbose_name='URL категории')),
            ],
            options={
                'verbose_name': 'Категории статьи',
                'verbose_name_plural': 'Категории статьи',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=70, verbose_name='SEO Title')),
                ('seo_description', models.CharField(max_length=140, verbose_name='SEO Description')),
                ('post_title', models.CharField(max_length=100, verbose_name='Заголовок статьи')),
                ('post_slug', models.SlugField(unique=True, verbose_name='URL cтатьи')),
                ('post_thumb_image', models.ImageField(upload_to='images/', verbose_name='Изобржение превью')),
                ('post_thumb_text', models.TextField(verbose_name='Текст превью')),
                ('post_date', models.DateField(default=datetime.date.today, verbose_name='Дата статьи')),
                ('post_file', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Видео или изображение статьи')),
                ('post_text', models.TextField(verbose_name='Содержимое статьи')),
                ('post_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.category', verbose_name='Категория статьи')),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
