# Generated by Django 4.1.3 on 2022-11-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_draft',
            field=models.BooleanField(default=True, verbose_name='Публикация новости'),
        ),
    ]
