# Generated by Django 4.1.3 on 2022-12-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.comments', verbose_name='Коментарий для ответа'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='post.post', verbose_name='Пост'),
        ),
    ]
