# Generated by Django 4.1.3 on 2022-12-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_comments_comment_parent_alter_comments_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='post.post', verbose_name='Пост'),
        ),
    ]
